import { StyleSheet } from "react-native";

import { CARD, MENU_DRAWER_RADIUS, MUTED, PAGE, PURPLE, TEXT } from "./homeTheme";

export const homeStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: PAGE,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  loadingHint: {
    marginTop: 12,
    color: MUTED,
    fontSize: 15,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: TEXT,
    textAlign: "center",
  },
  errorBody: {
    marginTop: 8,
    fontSize: 15,
    color: MUTED,
    textAlign: "center",
  },
  primaryBtn: {
    marginTop: 20,
    backgroundColor: PURPLE,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 999,
  },
  primaryBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  textBtn: {
    marginTop: 16,
    padding: 8,
  },
  textBtnLabel: {
    color: PURPLE,
    fontWeight: "600",
    fontSize: 15,
  },
  topRowSpacer: {
    flex: 1,
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#f1f5f9",
  },
  topRowGlass: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  menuBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  menuBtnText: {
    color: TEXT,
    fontSize: 18,
    fontWeight: "700",
  },
  greeting: {
    marginTop: 2,
    fontSize: 22,
    fontWeight: "700",
    color: TEXT,
    letterSpacing: -0.2,
  },
  greetingKicker: {
    marginTop: 18,
    fontSize: 12,
    fontWeight: "700",
    color: "#6366f1",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  greetingName: {
    fontWeight: "800",
    color: "#312e81",
  },
  subGreeting: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 20,
    color: MUTED,
  },
  rowActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
    marginBottom: 16,
  },
  glassBtnFill: {
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  outlineBtnText: {
    fontWeight: "700",
    color: TEXT,
    fontSize: 15,
  },
  solidBtnText: {
    fontWeight: "700",
    color: "#fff",
    fontSize: 15,
  },
  heroCardInner: {
    padding: 20,
  },
  heroCarousel: {
    marginBottom: 8,
  },
  heroCarouselContent: {
    paddingHorizontal: 0,
    gap: 0,
  },
  heroSlide: {},
  heroLabel: {
    color: "#c4b5fd",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  heroScore: {
    marginTop: 10,
    color: "#fff",
    fontSize: 28,
    fontWeight: "800",
  },
  heroScoreSub: {
    fontSize: 14,
    fontWeight: "500",
    color: "#ddd6fe",
  },
  heroDetail: {
    marginTop: 12,
    fontSize: 14,
    lineHeight: 20,
    color: "#e9d5ff",
  },
  warningList: {
    marginTop: 12,
  },
  warningItem: {
    fontSize: 13,
    color: "#fde68a",
    marginTop: 4,
  },
  heroMiniTrack: {
    marginTop: 14,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
  },
  heroMiniFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: "#7dd3fc",
  },
  heroDots: {
    flexDirection: "row",
    marginTop: 6,
    marginBottom: 12,
    gap: 6,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  dotActive: {
    width: 18,
    backgroundColor: "#fff",
  },
  metricsRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  metricCardInner: {
    padding: 16,
  },
  metricLabel: {
    fontSize: 13,
    color: MUTED,
    fontWeight: "600",
  },
  metricValue: {
    marginTop: 8,
    fontSize: 22,
    fontWeight: "800",
    color: TEXT,
  },
  sparkBar: {
    marginTop: 12,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#e2e8f0",
    overflow: "hidden",
  },
  sparkFill: {
    height: "100%",
    borderRadius: 3,
  },
  sectionTitle: {
    marginTop: 20,
    fontSize: 18,
    fontWeight: "800",
    color: TEXT,
  },
  sectionSub: {
    marginTop: 4,
    fontSize: 14,
    color: MUTED,
    marginBottom: 10,
  },
  listCardInner: {
    padding: 16,
  },
  txListWrap: {
    marginTop: 2,
  },
  trendCardInner: {
    padding: 16,
  },
  trendHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  trendLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#bfdbfe",
  },
  trendAmount: {
    fontSize: 14,
    fontWeight: "800",
    color: "#e0e7ff",
  },
  trendChartWrap: {
    height: 100,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "rgba(15,23,42,0.28)",
  },
  trendEmptyWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  recentRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingVertical: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#e2e8f0",
  },
  recentTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: TEXT,
  },
  recentMeta: {
    marginTop: 3,
    fontSize: 12,
    color: MUTED,
  },
  recentAmount: {
    fontSize: 14,
    fontWeight: "800",
    color: PURPLE,
  },
  pageScreenTitle: {
    marginTop: 4,
    fontSize: 24,
    fontWeight: "800",
    color: TEXT,
    letterSpacing: -0.4,
  },
  pageScreenSub: {
    marginTop: 6,
    fontSize: 14,
    color: MUTED,
    lineHeight: 20,
    marginBottom: 14,
  },
  dataRow: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "rgba(255,255,255,0.72)",
    marginBottom: 10,
  },
  dataRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  dataRowTopRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iconBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(91,33,182,0.08)",
  },
  iconBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: PURPLE,
  },
  crudToolbar: {
    alignSelf: "flex-start",
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: "rgba(91,33,182,0.12)",
  },
  crudToolbarText: {
    fontSize: 14,
    fontWeight: "700",
    color: PURPLE,
  },
  linkBtn: {
    fontSize: 14,
    fontWeight: "700",
    color: PURPLE,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 9,
    backgroundColor: "rgba(91,33,182,0.08)",
  },
  viewBtn: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 9,
    backgroundColor: "rgba(37,99,235,0.10)",
  },
  viewBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1d4ed8",
  },
  profileFieldLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: MUTED,
    marginTop: 10,
    marginBottom: 4,
  },
  profileInput: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: TEXT,
  },
  profileSaveBtn: {
    marginTop: 16,
    alignSelf: "flex-start",
    backgroundColor: PURPLE,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
  },
  profileSaveBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
  dataRowTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    color: TEXT,
  },
  dataRowAmount: {
    fontSize: 15,
    fontWeight: "800",
    color: PURPLE,
  },
  txDivider: {
    marginTop: 10,
    marginBottom: 8,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "#e2e8f0",
  },
  txBottomRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 8,
  },
  txMetaCol: {
    flex: 1,
  },
  txAmountRed: {
    fontSize: 16,
    fontWeight: "800",
    color: "#dc2626",
  },
  txCategoryBadge: {
    marginTop: 6,
    alignSelf: "flex-start",
    backgroundColor: "rgba(139,92,246,0.14)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  txCategoryBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#6d28d9",
  },
  dataRowMeta: {
    marginTop: 6,
    fontSize: 13,
    color: MUTED,
  },
  dataRowFine: {
    marginTop: 4,
    fontSize: 12,
    color: "#94a3b8",
  },
  dataBadge: {
    fontSize: 11,
    fontWeight: "700",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    overflow: "hidden",
  },
  dataBadgeOn: {
    backgroundColor: "#dcfce7",
    color: "#166534",
  },
  dataBadgeOff: {
    backgroundColor: "#f1f5f9",
    color: "#64748b",
  },
  colorSwatch: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#e2e8f0",
  },
  kvRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    gap: 12,
  },
  kvLabel: {
    fontSize: 14,
    color: MUTED,
    flex: 1,
  },
  kvValue: {
    fontSize: 14,
    fontWeight: "600",
    color: TEXT,
    textAlign: "right",
    flexShrink: 0,
    maxWidth: "52%",
  },
  profileCardInner: {
    flexDirection: "row",
    padding: 16,
    alignItems: "flex-start",
  },
  profileCardAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#f1f5f9",
  },
  profileCardCol: {
    flex: 1,
    marginLeft: 14,
  },
  profileCardName: {
    fontSize: 17,
    fontWeight: "800",
    color: TEXT,
  },
  profileCardEmail: {
    marginTop: 4,
    fontSize: 13,
    color: MUTED,
  },
  profileDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "#e2e8f0",
    marginVertical: 12,
  },
  emptyText: {
    color: MUTED,
    fontSize: 15,
  },
  catRow: {
    marginBottom: 14,
  },
  catLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  catName: {
    fontSize: 14,
    fontWeight: "600",
    color: TEXT,
    flex: 1,
    marginRight: 8,
  },
  catAmt: {
    fontSize: 14,
    fontWeight: "700",
    color: PURPLE,
  },
  catTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ede9fe",
    overflow: "hidden",
  },
  catFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: PURPLE,
  },
  insightLine: {
    fontSize: 15,
    color: MUTED,
    marginBottom: 8,
  },
  insightStrong: {
    fontWeight: "700",
    color: TEXT,
  },
  menuRoot: {
    flex: 1,
    flexDirection: "row",
  },
  menuPanelClip: {
    width: "75%",
    height: "100%",
    borderTopRightRadius: MENU_DRAWER_RADIUS,
    borderBottomRightRadius: MENU_DRAWER_RADIUS,
    overflow: "hidden",
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  menuPanel: {
    flex: 1,
    height: "100%",
  },
  menuPanelInnerWrap: {
    flex: 1,
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  menuBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  menuLogo: {
    width: 40,
    height: 40,
  },
  menuBrandTextCol: {
    flex: 1,
    marginLeft: 10,
  },
  menuBrandName: {
    fontSize: 16,
    fontWeight: "800",
    color: TEXT,
    letterSpacing: -0.3,
  },
  menuSubtitle: {
    marginTop: 2,
    marginBottom: 6,
    fontSize: 10,
    color: MUTED,
    lineHeight: 14,
  },
  menuItems: {
    flex: 1,
  },
  menuItem: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginBottom: 3,
  },
  menuItemActive: {
    backgroundColor: "rgba(139,92,246,0.14)",
  },
  menuItemText: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "600",
  },
  menuItemTextActive: {
    color: PURPLE,
  },
  menuItemSub: {
    marginTop: 1,
    fontSize: 10,
    color: "#64748b",
    lineHeight: 13,
  },
  menuSignOutInner: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  menuSignOutText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#b91c1c",
    textAlign: "center",
  },
  accountCardInner: {
    padding: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  accountAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#e2e8f0",
  },
  accountTextWrap: {
    marginLeft: 10,
    flex: 1,
  },
  accountName: {
    fontSize: 12,
    fontWeight: "700",
    color: TEXT,
  },
  accountEmail: {
    marginTop: 1,
    fontSize: 10,
    color: MUTED,
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: "transparent",
  },
});
